name: Publish to Test PyPI

on:
  push:
    branches: [main]
    paths:
      - 'zenith/**'
      - 'pyproject.toml'
      - 'setup.py'
  workflow_dispatch:

jobs:
  test-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: |
        uv pip install twine

    - name: Build package
      run: uv build
    
    - name: Check package
      run: |
        twine check dist/*
        python -m zipfile -l dist/*.whl
    
    - name: Publish to Test PyPI
      if: github.ref == 'refs/heads/main'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/* --skip-existing
      continue-on-error: true
    
    - name: Test installation from Test PyPI
      if: github.ref == 'refs/heads/main'
      run: |
        uv pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ zenithweb
      continue-on-error: true